version: '3.7'
services: 
  portainer:
    image: portainer/portainer
    container_name: 2021-portainer
    volumes: 
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports: 
      - 9000:9000
